arbstudio upgrade
nulinspiratie/SilQ pull request #190
Opened 2020-04-16 22:53 UTC by nulinspiratie

Requires merging PR https://github.com/nulinspiratie/Qcodes/pull/76

Changes:
- Change minimum sine pulse frequency from 1 MHz to 100 Hz
- Add parameter `force_upload_waveform` (default False), which when False does not upload waveforms if they are identical to the ones already uploaded
- Performance improvement to pulse sequence targeting. The old method was very slow for pulse sequences with many pulses.
- Incorporate arbstudio channels  (PR https://github.com/nulinspiratie/Qcodes/pull/76)
- Proper sine pulse generation

2020-09-03 04:12 UTC, RostyslavSavytskyy requested changes

2020-09-03 05:01 UTC, RostyslavSavytskyy requested changes

2020-09-08 01:03 UTC, nulinspiratie commented on silq/instrument_interfaces/lecroy/ArbStudio1104_interface.py
> +            pulse_requirements=[('frequency', {'min': 1e2, 'max': 125e6})]),
Agreed, fixed

2020-09-08 01:04 UTC, nulinspiratie commented on silq/instrument_interfaces/lecroy/ArbStudio1104_interface.py
> +                      "from the pulse that triggers the Arbstudio"
Replaced "pulse" by "interface", it should be clear now. If not, please let me know a better description

2020-09-08 01:04 UTC, nulinspiratie commented on silq/instrument_interfaces/lecroy/ArbStudio1104_interface.py
> +        self.trigger_in_duration = Parameter(
yes we'll discuss

2020-09-08 01:12 UTC, nulinspiratie commented on silq/instrument_interfaces/lecroy/ArbStudio1104_interface.py
> +                      'four points'
Yep good point, I have modified the docstring. Have a look if it's clearer now

2020-09-08 01:14 UTC, nulinspiratie commented on silq/instrument_interfaces/lecroy/ArbStudio1104_interface.py
>                      self.pulse_sequence.add(dc_pulse)
I think this part of the code works pretty much the same way as before, just more efficient. DC pulses at 0V were always added to bridge gaps between pulses

2020-09-08 01:15 UTC, nulinspiratie commented on silq/instrument_interfaces/lecroy/ArbStudio1104_interface.py
Not really, I don't think burst mode would work for our purposes

2020-09-08 01:15 UTC, nulinspiratie commented on silq/instrument_interfaces/lecroy/ArbStudio1104_interface.py
fixed

2020-09-08 01:15 UTC, nulinspiratie commented on silq/instrument_interfaces/lecroy/ArbStudio1104_interface.py
at least now abs(frequency) must be larger than 100. Else the implementation fails.

2020-09-08 01:18 UTC, nulinspiratie commented on silq/instrument_interfaces/lecroy/ArbStudio1104_interface.py
> +                self.pulse.frequency = modified_frequency
Yeah I think so, the frequency would be a tiny bit off, so I temporarily modify it to ensure the waveform has a full period.
The reason for only doing this at low-ish frequencies is that above this value, the change in frequency due to just a single point may be significant. Added a comment to clarify this

2020-09-08 01:23 UTC, nulinspiratie commented on silq/instrument_interfaces/lecroy/ArbStudio1104_interface.py
> +                voltages = self.pulse.get_voltage(t_list)
What was the error? I added a comment to clarify

2020-09-09 01:35 UTC, RostyslavSavytskyy commented on silq/instrument_interfaces/lecroy/ArbStudio1104_interface.py
> +                      'four points'
good

2020-09-09 01:38 UTC, RostyslavSavytskyy commented on silq/instrument_interfaces/lecroy/ArbStudio1104_interface.py
>                      self.pulse_sequence.add(dc_pulse)
ok

2020-09-09 01:38 UTC, RostyslavSavytskyy commented on silq/instrument_interfaces/lecroy/ArbStudio1104_interface.py
great

2020-09-09 01:43 UTC, RostyslavSavytskyy commented on silq/instrument_interfaces/lecroy/ArbStudio1104_interface.py
> +                voltages = self.pulse.get_voltage(t_list)
I already don't remember explicitly, can test it later

2020-09-09 01:43 UTC, RostyslavSavytskyy approved these changes

2020-09-09 01:44 UTC, RostyslavSavytskyy commented
Looks good to me

2020-09-10 01:51 UTC, merged